### ISSUE TITLE
How install via Portainer (Docker Composer) /Stacks

### ISSUE THREAD

**Issue by rah66** [kadrim/proxy4plex#11]
I am a beginner and not very good at all these Dockers, could you write an instruction on how to install via Portainer (Docker Composer) /Stacks.
As an example, it was easier for me to install Transmission and Plex according to similar instructions: 
https://hub.docker.com/r/linuxserver/transmission
https://hub.docker.com/r/linuxserver/plex

**Comment by kadrim** [comment]
sorry, this is out of scope for me. just use the binary as-is or get aquainted to docker.

if you really think, something like Portainer is useful for others, then read the docs, make it work and share your work by forking this repo, changing the README.md and then create a Pull-Request so that i can easily merge your additions.

This is how opensource works, everyone can participate 😃

**Comment by kadrim** [comment]
if you are up to the task and want to contribute, feel free to comment here. If you have a PR ready for merge, i will reopen this issue
